### ISSUE TITLE
ruby ba to?

### ISSUE THREAD

**Issue by faststare** [jjuliano/bato#12]
^^

**Comment by MKThayn** [comment]
Yup

**Comment by dreinavarro** [comment]
Dapat "Rubi" na lang

![rubi-2010-telenovela-33895d97-22de-47b0-8a75-780ef7626f7-resize-750](https://user-images.githubusercontent.com/96253/63995270-890e6e00-cb2a-11e9-8407-e4f17df21fc0.jpeg)

**Comment by losxmo19** [comment]
saan po magcocode neto? what IDE po?

**Comment by losxmo19** [comment]
![image](https://user-images.githubusercontent.com/76273126/102706786-e73b0380-42cf-11eb-80fd-2f02d569f48a.png)
bat ganto po ayaw gumana sakin. how to fix po?
