### ISSUE TITLE
Hello World program?

### ISSUE THREAD

**Issue by wolframroesler** [jjuliano/bato#6]
Hello, I'm the maintainer of the Hello World Collection, the Internet's greatest collection of Hello World programs, at http://helloworldcollection.de. I'd like to put Bato in to the collection but I don't understand anything you write on your site. Can you give me a simple Hello World program in Bato? Thanks!

**Comment by jjuliano** [comment]
Hi, thank you for this opportunity for Bato to be included in the Hello World Collection.

The program would be

`
# Hello World in Bato
mag_print "Hello World!"
`

Thanks,
Joel

**Comment by wolframroesler** [comment]
Thanks :) it's in the Collection now.

http://helloworldcollection.de
