### ISSUE TITLE
Transpiling

### ISSUE THREAD

**Issue by DJDaveMark** [jjuliano/bato#7]
A message for Juliano.

Would creating a transpiler be of any help? That way, any programming language could be coded in any native language, then transpiled to the original American-English version to be compiled. This can also be added to IDEs like Eclipse etc.

For example, TypeScript and CoffeeScript are both transpiled to JavaScript, but it would be very easy to do this for any language if the only things to transpile is the list of keywords. Here's an example of a hello world example in Java in French:

```
package java.outil.lang;

publique classe BonjourLeMonde {
    publique statique vide principal(Chaine args) {
        Système.sortie.imprimerLigne("Bonjour le monde !");
    }
}
```

**Comment by jjuliano** [comment]
Hello Dave,

That would be an interesting, however Bato is designed as an educational tool for Filipino people below the status quo to learn programming faster. If you have the spare time to implement that or help improve Bato, that would be great!
