### ISSUE TITLE
Bakit mag_print?

### ISSUE THREAD

**Issue by gcatipon** [jjuliano/bato#8]
I like this bato a lot and have worked with a few programming languages and am fascinated by your project. But being bilingual I wonder why you chose mag_print. This seems to me disaffective, a dissonant note. The word limbag translates to print so I was wondering why you didn't choose it. I guess this isn't much of a issue really if true native speakers are used to mag_print and not limbag. Salamat.

**Comment by Nullstr1ng** [comment]
mag_print is acceptable since everyone understands what "print" is. "Limbag" never heard of it before so its maybe confusing to others. Wag na siguro ung sobrang lalim na Tagalog words. *isulat* is pretty much acceptable

**Comment by ObeeWanKenobee** [comment]
`ipakita` I suppose..

**Comment by makoru-hikage** [comment]
@Nullstr1ng , "Limbag" is "publishing". Print in Filipino is "tatak". "Imprinted on one's mind" means "Tumatak sa kaisipan ng isa"

**Comment by MKThayn** [comment]
Baka makakatulong ako sa talakayan na ito :).

Una, salamat sa lumikha ng proyekto na ito. Napakaastig talaga!

1. Opo limbag ay print. Ito ang pinakakatumbas ng salitang print. Mas ginagamit ang salitang lathala para sa publish. Halimbawa ito ang nakasalita sa aklat: Moymoy Lulumboy ni Segundo Matias: Inilathala ng Lampara Publishing House, Inc.... Unang limbag ng unang edisyon, 2015. Gawa at limbag sa Maynila, Pilipinas.

2. Mag-print ay Filipino hindi Taglish. Opo galing sa wikang Ingles ang print pero natanggap nito sa opisyal na bokabularyo ng wikang Filipino: 

https://diksiyonaryo.ph/search/print 
Ang kawing na ito ay pumupunta sa opsiyal na diksyonaryo ng Komisyon sa Wikang Filipino. 

Edi kung sabihin ko: "Magpaprint ako ng kopya ng libro na ito tungkol sa mga bangkota sa dagat" Meron doon: 1 salitang Ingles, 2 Salitang Espanyol, 1 salitang Ilocano, at 10 Tagalog ngunit 100% Filipino ang pangungusap na ito dahil lahat ng salita dito'y tinatanggap sa lexicon ng Filipino at tama ito sa mga alintuntunin ng gramatikang Tagalog. "I went to the store kasi may sale na doon" Taglish naman yon.

3. Huwag po nating matakot gamiting "malalim na salita" Walang puntos mag-aral kung takot tayo sa kaalaman ;). Lalo kung kailangan ninyo ng salita na hindi natatagpuan sa wikang Tagalog pero mayroon sa wikang Filipino. Walang malalim dito sa Amerika ni Pranses meron lang mga salita alam namin at mga salita matututo pa :D.

Sana po nakakaambag ako sa usapan ninyo. Pasensiya kung mali ang Filipino ko hindi ako taga-Filipinas kaya hindi Filipino ang sinususong wika ko (Mother Tongue).

**Comment by hamuelxd12** [comment]
No, this language is dumb. Y should we use it?

**Comment by gcatipon** [comment]
Ako ay buong pusong nagpapasalamat sa inyo at saong ayon na mag_print tayo.
